### ISSUE TITLE
Are all the packs on the website copyrighted by Cards Against Humanity ?

### ISSUE THREAD

**Issue by mukberty** [crhallberg/json-against-humanity#28]
On the [site](https://crhallberg.com/cah/) , few packs are left unselected when I "`toggle official`". Have those been contributed by users or are they owned by Cards Against Humanity ?
Thanks a ton !

**Comment by crhallberg** [comment]
Good question! Cards Against Humanity is distributed under a Creative Commons license so this is all perfectly legal. The "Toggle Official" button makes it easier to choose only the decks that CAH has produced themselves, as opposed to the fan-generated and other unofficial content.

I think their website puts it best:

> Cards Against Humanity is available under a BY-NC-SA 2.0 Creative Commons license. That means you can use our content to make whatever, but you have to give us credit, you can’t profit from the use of our content (this means ad revenue is not allowed), and you have to share whatever you make in the same way we share it (this means you can’t submit our content to any app store). We own the name "Cards Against Humanity," so you have to call your crappy thing something else.

This is all clearer on the [v2 branch](https://github.com/crhallberg/json-against-humanity/tree/v2) which I'll be launching later this month. Thank you for your question!

**Comment by mukberty** [comment]
Wow. I understand what you have done is legal :+1: . I wanted to know whether the ones that are 
>fan-generated and other unofficial content

are owned by CAH , or can they be used by someone else for profit ?
Thanks again ;).

**Comment by crhallberg** [comment]
This repository is subject to CAH's license, so in order to use its content you need to follow the three restrictions of the CC BY-NC-SA 4.0 license:

- **Attribution (BY)** - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- **NonCommercial (NC)** - You may not use the material for commercial purposes.
- **ShareAlike (SA)** - If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

It would be a worthwhile endeavor to check each individual source's copyright status but my personal understanding is all fan and unofficial expansions are remixes of the copyleft licensed CAH content and is therefore also subject to the CC BY-NC-SA license.
